version: "3.8"
services:
  thevisual:
    build:
      dockerfile: ./Dockerfile
      context: .
    container_name: portfolio
    hostname: thevisual.work
    restart: unless_stopped
    ports:
      - "${HTTP_PORT:-80}:80"
      - "${HTTPS_PORT:-443}:443"
    environment:
      - TZ=America/Los_Angeles
    volumes:
      - logs:/var/log/nginx
      - certs:/etc/certs:ro

volumes:
  logs:
    name: logs
    driver: local
    driver_opts:
      type: none
      device: ${HOME}/logs/nginx
      o: bind
  certs:
    name: certs
    driver: local
    driver_opts:
      type: none
      device: ${HOME}/certs
      o: bind

networks:
  default:
    name: web
